### ISSUE TITLE
Sync 

### ISSUE THREAD

**Issue by DiskGetor** [fynelabs/notes#1]
How to sync for save notes or backup notes to current dir, because if reinstall system the notes will lost.

**Comment by andydotxyz** [comment]
Notes are saved into your fyne preference storage directory, which is platform specific.
There is also a way to sync using, for example, dropbox and a symlink (in 2.1 we plan to add proper cloud sync) - some thoughts on the matter at https://fynelabs.com/2021/04/20/keep-all-your-desktop-fyne-apps-in-sync/

**Comment by DiskGetor** [comment]
> Notes are saved into your fyne preference storage directory, which is platform specific.
> There is also a way to sync using, for example, dropbox and a symlink (in 2.1 we plan to add proper cloud sync) - some thoughts on the matter at https://fynelabs.com/2021/04/20/keep-all-your-desktop-fyne-apps-in-sync/

Ok
