### ISSUE TITLE
On iOS the main menu button overlays the "add note" button

### ISSUE THREAD

**Issue by inchworks** [fynelabs/notes#3]
The "+" in the toolbar isn't visible, so it isn't possible to add a note. The version in the Apple App Store works because it doesn't have a main menu. Removing the call to `w.SetMainMenu` reveals the "+" button.
<img width="551" alt="Screenshot 2023-08-02 at 18 51 19" src="https://github.com/fynelabs/notes/assets/53937883/18f0aab1-a62c-4e18-a101-46f1b74f4c3d">

**Comment by andydotxyz** [comment]
Thanks for the report. With a small update in Fyne and a tweak in #4 we should be good :)
